import { afterEach, describe, expect, it } from 'vitest'
import { GenerationSegmentError } from '@dreamverse/project'
import {
  FakeAssets,
  FakeGeneration,
  FakePromptEnhancer,
  holdPromptCall,
  promptResult,
  ref2vaFacts,
  referenceImage,
  within,
} from '../../project/tests/fakes.ts'
import { MEASURED_LATENCY, type FakeServices, type ProjectRun, type ProjectsHarness } from '../../project/tests/harness.ts'
import {
  finishRound,
  logEntry,
  openUserActions,
  projectPayload,
  REF2VA,
  roundStatus,
  segmentEntries,
  streamStart,
  UUID_V4,
} from './helpers.ts'

let harness: ProjectsHarness | undefined

afterEach(async () => {
  await harness?.dispose()
  harness = undefined
})

/**
 * Start a project whose completed sequence is `prompts`.
 * @param init - `project_init_v1` fields added to the default payload.
 * @param prompts - the curated prompts generated by the initial round.
 * @param services - the generation backend, asset library, and prompt enhancer fakes.
 * @returns the running project after its first round.
 */
async function startWithCompletedVideo(
  init: Record<string, unknown>,
  prompts: string[],
  services: FakeServices = {},
): Promise<ProjectRun> {
  harness = await openUserActions(services)
  const run = await harness.start(projectPayload({ curated_prompts: prompts, ...init }))
  await finishRound(run, prompts)
  return run
}

describe('append_prompt', () => {
  describe.each([true, false])('with enhancement %s', (enhance) => {
    it.each([['t2va', 5], ['t2va', 15], ['ref2va', 5], ['ref2va', 15]])(
      'appends one %s segment of %i seconds after the completed sequence', async (mode, duration) => {
        const assets = new FakeAssets()
        const assetIds = mode === 'ref2va' ? [assets.addImage('image').assetId] : []
        const run = await startWithCompletedVideo({
          model_id: mode === 'ref2va' ? 'h3-ref2va' : 'fast-ltx23', generation_mode: mode, segment_duration_sec: duration,
          enhancement_enabled: enhance, reference_asset_ids: assetIds,
        }, ['Accepted scene'], { generation: new FakeGeneration(mode === 'ref2va' ? ref2vaFacts() : undefined), assets })
        const [preceding] = run.project.completedSequenceSegmentIds
        const after = run.socket.entries.length
        await run.project.processBrowserCommand({
          type: 'append_prompt', prompt_id: 'continue', prompt: 'Follow the fox', reference_asset_ids: assetIds,
        })
        const call = await run.generation.nextCall()
        const prompt = enhance ? 'Following scene' : 'Follow the fox'
        // A first-frame model continues from its predecessor's handle; a reference model starts an independent shot.
        expect(call.request).toMatchObject({
          prompt, segmentIdx: 2, continueFrom: mode === 'ref2va' ? null : 'continuation-1',
          referenceImages: assetIds.map(id => referenceImage(id)),
        })
        expect(run.project.completedSequenceHistory).toEqual([[preceding]])
        call.finish.resolve()
        await run.socket.waitForStatus('idle', after)
        const source = enhance ? 'user_enhanced' : 'user_raw'
        expect(run.socket.entries.slice(after)).toEqual([
          roundStatus('preparing'),
          { type: 'prompt_received', prompt_id: 'continue' },
          ...(enhance ? [{ type: 'prompt_enhancing', prompt_id: 'continue' }] : []),
          { type: 'prompt_ready', prompt_id: 'continue', prompt, source },
          roundStatus('generating'),
          streamStart('continue', 'Follow the fox', ['Accepted scene', prompt], true),
          ...segmentEntries(2, source, null, 'continue'),
          { type: 'ltx2_stream_complete' },
          roundStatus('idle'),
        ])
        const appended = run.project.completedSequenceSegments[1]!
        expect(run.project.completedSequenceHistory).toEqual([[preceding], [preceding, appended.segmentId]])
        expect(appended).toMatchObject({ prompt, source: 'user', enhanced: enhance, sequenceIndex: null })
        expect(appended.instruction).toEqual({ requestId: 'continue', text: 'Follow the fox' })
        expect(appended.referenceSegmentId).toBe(mode === 'ref2va' ? null : preceding)
        if (enhance) {
          expect(harness!.enhancer.continueVideo.mock.calls).toEqual([['Follow the fox', {
            lockedSegments: ['Accepted scene'], nextSegmentIdx: 2, model: 'model-a', timeoutMs: 20000,
            generationMode: mode, segmentDurationSec: duration, referenceLabels: assetIds.map(() => 'Picture 1'),
            signal: run.project.generationSignal,
          }]])
          expect(harness!.logEvents('rewrite_done')).toEqual([logEntry('rewrite_done', {
            kind: 'enhance_prompt', latency_ms: 3.46, response: 'Following scene', error: null,
            fallback_used: false, provider: 'test', model: 'model-a',
          })])
        } else {
          expect(harness!.enhancer.continueVideo).not.toHaveBeenCalled()
        }
        expect(harness!.enhancer.expandClip).not.toHaveBeenCalled()
        expect(harness!.logEvents('enhance_request')).toEqual([logEntry('enhance_request', {
          prompt_id: 'continue', raw_prompt: 'Follow the fox', enhancement_enabled: enhance, rewrite_model: 'model-a',
        })])
        expect(harness!.logEvents('append_prompt')).toEqual([
          logEntry('append_prompt', { prompt: 'Follow the fox', source }),
        ])
        expect(harness!.logEvents('segment_complete').at(-1)).toEqual(logEntry('segment_complete', {
          segment_idx: 2, data_size_bytes: 8,
          latency_ms: MEASURED_LATENCY,
        }))
      })
  })

  it('rejects a continuation before any completed video', async () => {
    harness = await openUserActions()
    const run = await harness.start(projectPayload({ curated_prompts: [], enhancement_enabled: true }))
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt_id: 'continue', prompt: 'Follow the fox' })
    await run.socket.waitForStatus('failed', after)
    expect(run.socket.entries.slice(after)).toEqual([
      roundStatus('preparing'),
      { type: 'prompt_received', prompt_id: 'continue' },
      { type: 'prompt_enhancing', prompt_id: 'continue' },
      { type: 'error', message: 'Generate a video before requesting a continuation.', prompt_id: 'continue' },
      roundStatus('failed'),
    ])
    expect(harness.enhancer.continueVideo).not.toHaveBeenCalled()
    expect(run.project.videoSegmentsById.size).toBe(0)
  })

  it('rejects an empty continuation prompt', async () => {
    const run = await startWithCompletedVideo({}, ['A'])
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt_id: 'continue', prompt: '  ' })
    await run.socket.waitForStatus('failed', after)
    expect(run.socket.entries.slice(after)).toEqual([
      roundStatus('preparing'),
      { type: 'prompt_received', prompt_id: 'continue' },
      { type: 'error', message: 'A video continuation requires a prompt.', prompt_id: 'continue' },
      roundStatus('failed'),
    ])
  })

  describe.each(['fallback', 'provider_exception'])('%s failure', (failure) => {
    it('ends the prompt lifecycle with an error before registering a segment', async () => {
      const enhancer = new FakePromptEnhancer()
      if (failure === 'fallback') {
        enhancer.continueVideo.mockResolvedValueOnce(promptResult('Following scene', { fallbackUsed: true, error: 'Provider unavailable' }))
      } else {
        enhancer.continueVideo.mockRejectedValueOnce(new Error('Provider unavailable'))
      }
      const run = await startWithCompletedVideo({ enhancement_enabled: true }, ['A'], { enhancer })
      const segmentCount = run.project.videoSegmentsById.size
      const after = run.socket.entries.length
      await run.project.processBrowserCommand({ type: 'append_prompt', prompt_id: 'prompt', prompt: 'Follow the fox' })
      await run.socket.waitForStatus('failed', after)
      const message = 'Prompt extension failed for this request.'
      expect(run.socket.entries.slice(after)).toEqual([
        roundStatus('preparing'),
        { type: 'prompt_received', prompt_id: 'prompt' },
        { type: 'prompt_enhancing', prompt_id: 'prompt' },
        { type: 'error', message, prompt_id: 'prompt' },
        roundStatus('failed'),
      ])
      expect(run.project.videoSegmentsById.size).toBe(segmentCount)
      expect(run.project.completedSequencePrompts).toEqual(['A'])
      expect(run.generation.calls).toHaveLength(1)
      if (failure === 'fallback') {
        expect(harness!.logEvents('rewrite_done')).toEqual([logEntry('rewrite_done', {
          kind: 'enhance_prompt', latency_ms: 2.35, response: 'Following scene', error: 'Provider unavailable',
          fallback_used: true, provider: 'test', model: 'model-a',
        })])
      } else {
        expect(harness!.logEvents('rewrite_exception')).toEqual([logEntry('rewrite_exception', {
          kind: 'enhance_prompt', prompt_id: 'prompt', raw_prompt: 'Follow the fox', rewrite_model: 'model-a',
          error: 'Provider unavailable',
        })])
      }
    })
  })

  it('requires a rewrite before continuing a first-frame video after a failed round', async () => {
    const run = await startWithCompletedVideo({}, ['A'])
    run.generation.rejectSegments = new GenerationSegmentError('The worker rejected this shot.', 'ValueError', true)
    let after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'simple_generate', prompt: 'Rejected shot' })
    await run.socket.waitForStatus('failed', after)
    expect(run.project.generationPlanController.lastCompletedSegmentId).toBeNull()
    run.generation.rejectSegments = null
    after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt_id: 'continue', prompt: 'Next beat' })
    await run.socket.waitForStatus('failed', after)
    expect(run.socket.entries.slice(after)).toEqual([
      roundStatus('preparing'),
      {
        type: 'error', message: 'The previous generation failed. Rewrite the sequence before continuing it.',
        prompt_id: 'continue',
      },
      roundStatus('failed'),
    ])
    expect(run.generation.calls).toHaveLength(1)
  })

  it('appends an independent reference shot after a failed round without worker conditioning', async () => {
    const assets = new FakeAssets()
    assets.addImage('image')
    const run = await startWithCompletedVideo({
      ...REF2VA, reference_asset_ids: ['image'], preset_id: 'accepted-story', preset_label: 'Accepted story',
    }, ['First shot'], { generation: new FakeGeneration(ref2vaFacts()), assets })
    const acceptedIds = run.project.completedSequenceSegmentIds
    run.generation.rejectSegments = new GenerationSegmentError('The worker rejected this shot.', 'ValueError', true)
    let after = run.socket.entries.length
    await run.project.processBrowserCommand({
      type: 'simple_generate', prompt: 'Rejected shot', preset_id: 'replacement-story',
      preset_label: 'Replacement story', reference_asset_ids: ['image'],
    })
    await run.socket.waitForStatus('failed', after)
    expect(run.socket.eventsOfType('error', after)).toEqual([
      { type: 'error', message: 'The worker rejected this shot.', prompt_id: null },
    ])
    expect(run.project.generationPlanController.lastCompletedSegmentId).toBeNull()
    expect(run.project.completedSequenceHistory).toEqual([acceptedIds])
    expect([run.project.promptSequenceId, run.project.promptSequenceLabel]).toEqual(['accepted-story', 'Accepted story'])
    run.generation.rejectSegments = null
    after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt: 'Next story beat', reference_asset_ids: ['image'] })
    const following = await run.generation.nextCall()
    expect(following.request).toMatchObject({ segmentIdx: 2, continueFrom: null, referenceImages: [referenceImage('image')] })
    following.finish.resolve()
    await run.socket.waitForStatus('idle', after)
    expect(run.project.completedSequenceSegmentIds).toHaveLength(2)
  })

  it('starts an image-conditioned continuation from the selected first frame', async () => {
    const assets = new FakeAssets()
    const first = assets.addImage('first')
    assets.addImage('second')
    const run = await startWithCompletedVideo({
      generation_mode: 'i2v', reference_asset_ids: ['first'],
    }, ['A', 'A continued'], { assets })
    // The chained segment sends its predecessor's handle and no images.
    expect(run.generation.calls.map(call => [call.request.continueFrom, call.request.referenceImages]))
      .toEqual([[null, [referenceImage('first')]], ['continuation-1', []]])
    expect(run.project.completedSequenceSegments.map(segment => segment.referenceAssets)).toEqual([[first], [first]])
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt: 'B', reference_asset_ids: ['second'] })
    const call = await run.generation.nextCall()
    expect(call.request).toMatchObject({ segmentIdx: 3, continueFrom: null, referenceImages: [referenceImage('second')] })
    call.finish.resolve()
    await run.socket.waitForStatus('idle', after)
    expect(run.project.completedSequenceSegments[2]!.referenceSegmentId).toBeNull()
  })

  describe.each([true, false])('with enhancement %s', (enhance) => {
    it('reports the prompt lifecycle with stable IDs before submitting the prepared segment', async () => {
      const enhancer = new FakePromptEnhancer()
      const held = holdPromptCall(enhancer.continueVideo, () => promptResult('The fox reaches a stream'))
      const run = await startWithCompletedVideo({ enhancement_enabled: enhance }, ['A'], { enhancer })
      const after = run.socket.entries.length
      const readyHold = run.socket.hold('prompt_ready')
      await run.project.processBrowserCommand({ type: 'append_prompt', prompt_id: 'manual-continuation', prompt: 'Follow the fox' })
      if (enhance) {
        await within(held.entered.promise)
        expect(run.socket.events(after).filter(event => String(event['type']).startsWith('prompt_'))).toEqual([
          { type: 'prompt_received', prompt_id: 'manual-continuation' },
          { type: 'prompt_enhancing', prompt_id: 'manual-continuation' },
        ])
        expect(run.generation.calls).toHaveLength(1)
        held.release.resolve()
      }
      await within(readyHold.held.promise)
      expect(run.generation.calls).toHaveLength(1)
      if (!enhance) expect(enhancer.continueVideo).not.toHaveBeenCalled()
      readyHold.resume.resolve()
      const following = await run.generation.nextCall()
      const expectedPrompt = enhance ? 'The fox reaches a stream' : 'Follow the fox'
      expect(following.request.prompt).toBe(expectedPrompt)
      following.finish.resolve()
      await run.socket.waitForStatus('idle', after)
      expect(run.socket.events(after).filter(event => [
        'prompt_received', 'prompt_enhancing', 'prompt_ready', 'ltx2_stream_start', 'ltx2_segment_start',
      ].includes(String(event['type'])))).toEqual([
        { type: 'prompt_received', prompt_id: 'manual-continuation' },
        ...(enhance ? [{ type: 'prompt_enhancing', prompt_id: 'manual-continuation' }] : []),
        {
          type: 'prompt_ready', prompt_id: 'manual-continuation', prompt: expectedPrompt,
          source: enhance ? 'user_enhanced' : 'user_raw',
        },
        streamStart('manual-continuation', 'Follow the fox', ['A', expectedPrompt], true),
        {
          type: 'ltx2_segment_start', segment_idx: 2, source: enhance ? 'user_enhanced' : 'user_raw',
          seed_prompt_index: null, prompt_id: 'manual-continuation',
        },
      ])
    })
  })

  it.each([
    { type: 'append_prompt', prompt: 'another direction' },
    { type: 'rewrite_seed_prompts', rewrite_instruction: 'another rewrite' },
    { type: 'simple_generate', prompt: 'another clip' },
    { type: 'set_enhancement', enabled: false },
    { type: 'set_rewrite_model', rewrite_model: 'model-b' },
    { type: 'set_rewrite_temperature', rewrite_temperature: 0.9 },
  ])('rejects $type while the continuation prompt is prepared', async (command) => {
    const enhancer = new FakePromptEnhancer()
    const held = holdPromptCall(enhancer.continueVideo, () => promptResult('B'))
    const run = await startWithCompletedVideo({ enhancement_enabled: true }, ['A'], { enhancer })
    const settings = [run.project.promptEnhancementEnabled, run.project.promptEnhancementModel, run.project.sequencePromptTemperature]
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt: 'Continue A' })
    await within(held.entered.promise)
    const beforeCommand = run.socket.entries.length
    await run.project.processBrowserCommand(command)
    expect(run.socket.events(beforeCommand)).toEqual([{
      type: 'error', prompt_id: null, message: 'Wait for this generation round to finish before changing the video.',
    }])
    expect(run.project.generationRoundStatus).toBe('preparing')
    expect([run.project.promptEnhancementEnabled, run.project.promptEnhancementModel, run.project.sequencePromptTemperature])
      .toEqual(settings)
    held.release.resolve()
    const call = await run.generation.nextCall()
    call.finish.resolve()
    await run.socket.waitForStatus('idle', after)
    expect(run.project.completedSequencePrompts).toEqual(['A', 'B'])
    expect(enhancer.continueVideo.mock.calls.map(call => call[1].lockedSegments)).toEqual([['A']])
    expect(run.generation.calls).toHaveLength(2)
  })

  it('stops waiting for the provider on close without submitting more video', async () => {
    const enhancer = new FakePromptEnhancer()
    const held = holdPromptCall(enhancer.continueVideo, () => promptResult('Too late'))
    const run = await startWithCompletedVideo({ enhancement_enabled: true }, ['A'], { enhancer })
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt: 'Continue A' })
    await within(held.entered.promise)
    await within(run.project.closeAndWaitForGeneration())
    // The provider call observes the aborted signal; this fake ignores it and stays held after closure.
    expect(enhancer.continueVideo.mock.calls[0]![1].signal.aborted).toBe(true)
    expect(held.finished.settled).toBe(false)
    expect(await within(run.outcome)).toBeNull()
    expect(run.project.isClosed).toBe(true)
    held.release.resolve()
    await within(held.finished.promise)
    expect(run.generation.calls).toHaveLength(1)
    expect(run.project.completedSequencePrompts).toEqual(['A'])
    expect(harness!.logEvents('rewrite_exception')).toEqual([])
    expect(harness!.logEvents('generation_round_failed')).toEqual([])
  })

  it('holds the extended sequence until its segment succeeds', async () => {
    const run = await startWithCompletedVideo({}, ['Accepted scene'])
    const history = run.project.completedSequenceHistory.map(ids => [...ids])
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt: 'Follow the fox' })
    const call = await run.generation.nextCall()
    const plan = run.project.activeGenerationPlan!
    expect(plan.sequenceIds).toEqual([...history[0]!, ...plan.segmentIds])
    expect(plan.append).toBe(true)
    expect(run.project.completedSequenceHistory).toEqual(history)
    call.failWith = new GenerationSegmentError('Video generation failed', 'ValueError', true)
    call.finish.resolve()
    await run.socket.waitForStatus('failed', after)
    expect(run.project.completedSequenceHistory).toEqual(history)
    expect(run.socket.eventsOfType('error', after)).toEqual([
      { type: 'error', message: 'Video generation failed', prompt_id: null },
    ])
  })

  it('creates a UUID request ID and strips the prompt when the command has no prompt ID', async () => {
    const run = await startWithCompletedVideo({}, ['A'])
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt: ' Follow the fox ' })
    await finishRound(run, ['Follow the fox'])
    const instruction = run.project.completedSequenceSegments[1]!.instruction!
    expect(instruction.text).toBe('Follow the fox')
    expect(instruction.requestId).toMatch(UUID_V4)
    expect(run.socket.eventsOfType('prompt_received', after)).toEqual([{ type: 'prompt_received', prompt_id: instruction.requestId }])
  })

  it('labels the ordered reference images for the enhancer and shares them with the segment', async () => {
    const assets = new FakeAssets()
    const side = assets.addImage('side')
    const front = assets.addImage('front')
    const run = await startWithCompletedVideo({
      ...REF2VA, reference_asset_ids: ['side'], enhancement_enabled: true,
    }, ['A lake'], { generation: new FakeGeneration(ref2vaFacts()), assets })
    await run.project.processBrowserCommand({
      type: 'append_prompt', prompt_id: 'request', prompt: 'A protagonist walks', reference_asset_ids: ['side', 'front'],
    })
    await finishRound(run, ['Following scene'])
    expect(run.project.completedSequenceSegments[1]!.referenceAssets).toEqual([side, front])
    expect(harness!.enhancer.continueVideo.mock.calls[0]![1].referenceLabels).toEqual(['Picture 1', 'Picture 2'])
  })
})
