import { afterEach, describe, expect, it } from 'vitest'
import { GenerationSegmentError, type RolloutResult } from '@dreamverse/project'
import {
  Deferred,
  FakeAssets,
  FakeGeneration,
  FakePromptEnhancer,
  FakeSocket,
  ref2vaFacts,
  within,
} from '../../project/tests/fakes.ts'
import type { FakeServices, ProjectRun, ProjectsHarness } from '../../project/tests/harness.ts'
import {
  finishRound,
  logEntry,
  openUserActions,
  projectPayload,
  REF2VA,
  rolloutText,
  roundStatus,
  segmentEntries,
  streamStart,
  UUID_V4,
} from './helpers.ts'

let harness: ProjectsHarness | undefined

afterEach(async () => {
  await harness?.dispose()
  harness = undefined
})

/** Raw rollout text that the reference user-action tests attach to their rollouts. */
const DIAGNOSTIC_TEXT = '{"segment_prompts": "diagnostic response"}'

/**
 * A rollout like the reference `rollout_response`.
 * @param prompts - the rewritten prompts.
 * @param fields - result fields that replace the successful defaults.
 * @returns the rollout.
 */
function rollout(prompts: string[], fields: Partial<RolloutResult> = {}): RolloutResult {
  return {
    prompts, sourcePrompts: ['Accepted scene'], fallbackUsed: false, error: null, provider: 'test', model: 'model-a',
    latencyMs: 12.345, rolloutId: 'rewritten-sequence', rolloutLabel: 'Rewritten sequence',
    rawResponseText: DIAGNOSTIC_TEXT, ...fields,
  }
}

/**
 * Start a project whose completed sequence is `prompts`, with the reference test's accepted preset metadata.
 * @param prompts - the curated prompts generated by the initial round.
 * @param services - the generation backend, asset library, and prompt enhancer fakes.
 * @param init - `project_init_v1` fields added to the default payload.
 * @returns the running project after its first round.
 */
async function startWithAcceptedSequence(
  prompts: string[] = ['Accepted scene'],
  services: FakeServices = {},
  init: Record<string, unknown> = {},
): Promise<ProjectRun> {
  harness = await openUserActions(services)
  const run = await harness.start(projectPayload({
    curated_prompts: prompts, preset_id: 'accepted-sequence', preset_label: 'Accepted sequence', ...init,
  }))
  await finishRound(run, prompts)
  return run
}

describe('rewrite_seed_prompts', () => {
  it.each(['t2va', 'ref2va'])('captures the selected %s window for the provider and ignores browser rewrite settings', async (mode) => {
    const assets = new FakeAssets()
    const assetIds = mode === 'ref2va' ? [assets.addImage('image').assetId] : []
    const enhancer = new FakePromptEnhancer()
    const entered = new Deferred()
    const release = new Deferred()
    enhancer.rewriteRollout.mockImplementationOnce(async () => {
      entered.resolve()
      await release.promise
      return rollout(['Rewritten beach', 'Rewritten sunset'])
    })
    const generation = new FakeGeneration(mode === 'ref2va' ? ref2vaFacts() : undefined)
    const run = await startWithAcceptedSequence(['Accepted scene'], { generation, assets, enhancer }, {
      model_id: mode === 'ref2va' ? 'h3-ref2va' : 'fast-ltx23', generation_mode: mode, reference_asset_ids: assetIds,
    })
    const selectedWindow = ['Archived beach', 'Archived sunset']
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({
      type: 'rewrite_seed_prompts', prompt_id: 'rewrite', rewrite_instruction: 'Add rain',
      prompt_window_prompts: selectedWindow, rewrite_model: 'model-b', rewrite_temperature: 0.4,
      rewrite_window_system_prompt: 'rewrite template', rewrite_user_system_prompt: 'seed template',
      reference_asset_ids: assetIds,
    })
    await within(entered.promise)
    // The provider wait neither creates a plan nor changes accepted content.
    selectedWindow[0] = 'Edited after submission'
    expect(run.project.videoSegmentsById.size).toBe(1)
    expect(run.project.completedSequencePrompts).toEqual(['Accepted scene'])
    release.resolve()
    await finishRound(run, ['Rewritten beach', 'Rewritten sunset'])
    expect(enhancer.rewriteRollout.mock.calls).toEqual([[['Accepted scene'], {
      promptsToRewrite: ['Archived beach', 'Archived sunset'], presetId: 'accepted-sequence',
      presetLabel: 'Accepted sequence', rewriteInstruction: 'Add rain', timeoutMs: 20000, generationMode: mode,
      referenceLabels: assetIds.map(() => 'Picture 1'), segmentCount: 1, segmentDurationSec: 5,
      continuedSegmentLabels: mode === 'ref2va' ? { referenceLabels: ['Picture 1'], firstFrameLabel: 'Picture 2' } : null,
      signal: run.project.generationSignal,
    }]])
    expect([run.project.promptSequenceId, run.project.promptSequenceLabel]).toEqual(['rewritten-sequence', 'Rewritten sequence'])
    expect(run.project.promptEnhancementModel).toBe('model-a')
    const prompts = ['Rewritten beach', 'Rewritten sunset']
    expect(run.socket.entries.slice(after)).toEqual([
      roundStatus('preparing'),
      { type: 'seed_prompts_updated', prompts, model: 'model-a', latency_ms: 12.35, raw_llm_output: DIAGNOSTIC_TEXT },
      { type: 'rewrite_seed_prompts_complete', prompt_id: 'rewrite' },
      roundStatus('generating'),
      streamStart('rewrite', 'Add rain', prompts),
      ...segmentEntries(1, 'user_enhanced', 0, 'rewrite'),
      ...segmentEntries(2, 'user_enhanced', 1, 'rewrite'),
      { type: 'ltx2_stream_complete' },
      roundStatus('idle'),
    ])
    const segments = run.project.completedSequenceSegments
    expect(segments[1]!.referenceSegmentId).toBe(segments[0]!.segmentId)
    expect(harness!.logEvents('rewrite_done')).toEqual([logEntry('rewrite_done', {
      kind: 'seed_rewrite', rewrite_instruction: 'Add rain', latency_ms: 12.35, response: DIAGNOSTIC_TEXT,
    })])
  })

  describe.each(['fallback', 'empty'])('%s rewrite output', (failure) => {
    it('closes the rewrite with a terminal diagnostic and keeps accepted content', async () => {
      const enhancer = new FakePromptEnhancer()
      enhancer.rewriteRollout.mockResolvedValueOnce(failure === 'fallback'
        ? rollout(['Accepted scene'], { fallbackUsed: true, error: 'Provider unavailable' })
        : rollout([]))
      const run = await startWithAcceptedSequence(['Accepted scene'], { enhancer })
      const after = run.socket.entries.length
      await run.project.processBrowserCommand({ type: 'rewrite_seed_prompts', prompt_id: 'rewrite', rewrite_instruction: 'Add rain' })
      await run.socket.waitForStatus('failed', after)
      const error = failure === 'fallback' ? 'Provider unavailable' : 'Prompt rewrite failed for this request.'
      expect(run.socket.entries.slice(after)).toEqual([
        roundStatus('preparing'),
        { type: 'rewrite_seed_prompts_complete', prompt_id: 'rewrite', error, model: 'model-a', latency_ms: 12.35 },
        { type: 'error', message: error, prompt_id: 'rewrite' },
        roundStatus('failed'),
      ])
      expect(run.project.videoSegmentsById.size).toBe(1)
      expect(run.project.promptSequenceId).toBe('accepted-sequence')
      expect(harness!.logEvents('rewrite_done')).toEqual([logEntry('rewrite_done', {
        kind: 'seed_rewrite', rewrite_instruction: 'Add rain', latency_ms: 12.35, response: DIAGNOSTIC_TEXT,
      })])
    })
  })

  it('reports a recoverable provider failure and accepts a later rewrite', async () => {
    const enhancer = new FakePromptEnhancer()
    enhancer.rewriteRollout.mockRejectedValueOnce(new Error('Provider unavailable'))
    const run = await startWithAcceptedSequence(['Stored scene 1'], { enhancer })
    const after = run.socket.entries.length
    const command = { type: 'rewrite_seed_prompts', prompt_id: 'rewrite', rewrite_instruction: 'Change the lighting' }
    await run.project.processBrowserCommand(command)
    await run.socket.waitForStatus('failed', after)
    const error = 'Provider unavailable'
    expect(run.socket.entries.slice(after)).toEqual([
      roundStatus('preparing'),
      { type: 'rewrite_seed_prompts_complete', prompt_id: 'rewrite', error, model: 'model-a', latency_ms: 0 },
      { type: 'error', message: error, prompt_id: 'rewrite' },
      roundStatus('failed'),
    ])
    expect(harness!.logEvents('rewrite_exception')).toEqual([logEntry('rewrite_exception', {
      kind: 'seed_rewrite', rewrite_instruction: 'Change the lighting', rewrite_model: 'model-a',
      error: 'Provider unavailable',
    })])
    await run.project.processBrowserCommand({ type: 'set_enhancement', enabled: false })
    const retry = run.socket.entries.length
    await run.project.processBrowserCommand(command)
    await finishRound(run, ['Scene 1'])
    expect(run.socket.eventsOfType('rewrite_seed_prompts_complete', retry)).toEqual([
      { type: 'rewrite_seed_prompts_complete', prompt_id: 'rewrite' },
    ])
    expect(run.project.promptEnhancementEnabled).toBe(false)
    expect(run.project.completedSequencePrompts).toEqual(['Scene 1'])
    expect(enhancer.rewriteRollout).toHaveBeenCalledTimes(2)
    expect(run.project.isClosed).toBe(false)
  })

  it('ends the project when announcing the rewritten prompts fails, releasing the round references', async () => {
    const assets = new FakeAssets()
    assets.addImage('image')
    const run = await startWithAcceptedSequence(['Accepted scene'], { generation: new FakeGeneration(ref2vaFacts()), assets }, {
      ...REF2VA, reference_asset_ids: ['image'],
    })
    const history = run.project.completedSequenceHistory.map(ids => [...ids])
    run.socket.failNext('seed_prompts_updated', new Error('Socket closed'))
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({
      type: 'rewrite_seed_prompts', prompt_id: 'rewrite', rewrite_instruction: 'Add rain', reference_asset_ids: ['image'],
    })
    const outcome = await within(run.outcome)
    expect((outcome as Error).message).toBe('Socket closed')
    expect(run.socket.entries.slice(after)).toEqual([roundStatus('preparing'), roundStatus('failed')])
    expect([run.project.promptSequenceId, run.project.promptSequenceLabel]).toEqual(['accepted-sequence', 'Accepted sequence'])
    expect(run.project.completedSequenceHistory).toEqual(history)
    expect(run.generation.calls).toHaveLength(1)
    expect(assets.totalRetained()).toBe(0)
    expect(run.project.isClosed).toBe(true)
    expect(harness!.logEvents('generation_round_failed')).toEqual([
      logEntry('generation_round_failed', { action: 'rewrite_seed_prompts', error: 'Socket closed' }),
    ])
  })

  it('ends the project when reporting an initial rollout fallback fails', async () => {
    const assets = new FakeAssets()
    assets.addImage('image')
    const enhancer = new FakePromptEnhancer()
    enhancer.rewriteRollout.mockResolvedValueOnce(rollout([], {
      sourcePrompts: [], fallbackUsed: true, error: 'Controlled rewrite provider failed', rawResponseText: null,
    }))
    const socket = new FakeSocket()
    socket.failNext('rewrite_seed_prompts_complete', new Error('Rewrite result send failed'))
    harness = await openUserActions({ assets, enhancer })
    const run = await harness.start(projectPayload({
      generation_mode: 'i2v', reference_asset_ids: ['image'], initial_rollout_prompt: 'A boat crosses a lake',
    }), socket)
    const outcome = await within(run.outcome)
    expect((outcome as Error).message).toBe('Rewrite result send failed')
    expect(run.socket.entries).toEqual([roundStatus('preparing'), roundStatus('failed')])
    expect(run.generation.calls).toEqual([])
    expect(assets.totalRetained()).toBe(0)
    expect(harness.logEvents('rewrite_done')).toEqual([logEntry('rewrite_done', {
      kind: 'seed_rewrite', rewrite_instruction: 'A boat crosses a lake', latency_ms: 12.35, response: '',
    })])
  })

  it('accepts an empty instruction when completed prompts exist', async () => {
    const run = await startWithAcceptedSequence()
    await run.project.processBrowserCommand({ type: 'rewrite_seed_prompts', prompt_id: 'rewrite', rewrite_instruction: '' })
    await finishRound(run, ['Scene 1'])
    const [prompts, options] = harness!.enhancer.rewriteRollout.mock.calls[0]!
    expect([prompts, options.rewriteInstruction]).toEqual([['Accepted scene'], ''])
  })

  it('rejects a rewrite without prompts or an instruction', async () => {
    harness = await openUserActions()
    const run = await harness.start(projectPayload({ curated_prompts: [] }))
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'rewrite_seed_prompts', prompt_id: 'rewrite', rewrite_instruction: ' ' })
    await run.socket.waitForStatus('failed', after)
    expect(run.socket.entries.slice(after)).toEqual([
      roundStatus('preparing'),
      { type: 'error', message: 'A sequence rewrite requires prompts or an instruction.', prompt_id: 'rewrite' },
      roundStatus('failed'),
    ])
    expect(harness.enhancer.rewriteRollout).not.toHaveBeenCalled()
  })

  it.each([
    ['worker error', new GenerationSegmentError('Video generation failed', 'RuntimeError', false)],
    ['value error', new GenerationSegmentError('Video generation failed', 'ValueError', true)],
  ])('restores accepted metadata and records nothing after a %s', async (_label, failure) => {
    const run = await startWithAcceptedSequence()
    const history = run.project.completedSequenceHistory.map(ids => [...ids])
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'rewrite_seed_prompts', prompt_id: 'rewrite', rewrite_instruction: 'Add rain' })
    const call = await run.generation.nextCall()
    expect([run.project.promptSequenceId, run.project.promptSequenceLabel]).toEqual(['test-scenes', 'Test scenes'])
    expect(run.project.activeGenerationPlan!.sequenceIds).toEqual(run.project.activeGenerationPlan!.segmentIds)
    expect(run.project.completedSequenceHistory).toEqual(history)
    call.failWith = failure
    call.finish.resolve()
    await run.socket.waitForStatus('failed', after)
    expect([run.project.promptSequenceId, run.project.promptSequenceLabel]).toEqual(['accepted-sequence', 'Accepted sequence'])
    expect(run.project.completedSequenceHistory).toEqual(history)
    expect(run.socket.eventsOfType('error', after)).toEqual(failure.isValueError
      ? [{ type: 'error', message: 'Video generation failed', prompt_id: 'rewrite' }]
      : [])
  })

  it('creates a UUID request ID and strips the instruction when the command has no prompt ID', async () => {
    const run = await startWithAcceptedSequence()
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'rewrite_seed_prompts', rewrite_instruction: ' Add rain ' })
    await finishRound(run, ['Scene 1'])
    const instruction = run.project.completedSequenceSegments[0]!.instruction!
    expect(instruction.text).toBe('Add rain')
    expect(instruction.requestId).toMatch(UUID_V4)
    expect(run.socket.eventsOfType('rewrite_seed_prompts_complete', after)).toEqual([
      { type: 'rewrite_seed_prompts_complete', prompt_id: instruction.requestId },
    ])
  })

  it('labels the ordered reference images for the provider and shares them with every segment', async () => {
    const assets = new FakeAssets()
    const side = assets.addImage('side')
    const front = assets.addImage('front')
    const run = await startWithAcceptedSequence(['A lake'], { generation: new FakeGeneration(ref2vaFacts()), assets }, {
      ...REF2VA, reference_asset_ids: ['side'],
    })
    await run.project.processBrowserCommand({
      type: 'rewrite_seed_prompts', prompt_id: 'request', rewrite_instruction: 'A protagonist walks',
      reference_asset_ids: ['side', 'front'],
    })
    await finishRound(run, ['Scene 1'])
    expect(run.project.completedSequenceSegments[0]!.referenceAssets).toEqual([side, front])
    expect(harness!.enhancer.rewriteRollout.mock.calls[0]![1].referenceLabels).toEqual(['Picture 1', 'Picture 2'])
  })

  it.each([[null], [[]], [['  ', null, 7]], ['invalid window']])(
    'rewrites the accepted sequence when the browser window is %j', async (browserWindow) => {
      const prompts = ['Stored scene 1', 'Stored scene 2']
      const run = await startWithAcceptedSequence(prompts)
      const originalIds = run.project.completedSequenceSegmentIds
      await run.project.processBrowserCommand({
        type: 'rewrite_seed_prompts', rewrite_instruction: 'Make it cinematic', prompt_window_prompts: browserWindow,
      })
      await finishRound(run, ['Scene 1', 'Scene 2'])
      const [source, options] = harness!.enhancer.rewriteRollout.mock.calls[0]!
      expect([source, options.promptsToRewrite, options.rewriteInstruction]).toEqual([prompts, browserWindow, 'Make it cinematic'])
      expect(run.project.completedSequenceSegmentIds).not.toEqual(originalIds)
      expect(originalIds.map(id => run.project.videoSegmentsById.get(id)!.status)).toEqual(['completed', 'completed'])
    })

  it('rewrites a selected archived window instead of the accepted sequence', async () => {
    const run = await startWithAcceptedSequence(['Accepted forest'])
    await run.project.processBrowserCommand({
      type: 'rewrite_seed_prompts', rewrite_instruction: 'Add rain', prompt_window_prompts: ['Archived beach', 'Archived sunset'],
    })
    await finishRound(run, ['Scene 1', 'Scene 2'])
    expect(harness!.enhancer.rewriteRollout.mock.calls[0]![1].promptsToRewrite).toEqual(['Archived beach', 'Archived sunset'])
    expect(run.project.completedSequenceHistory).toHaveLength(2)
  })

  it('preserves a seven-segment sequence that grew past the initial selection', async () => {
    const presets = Array.from({ length: 6 }, (_value, index) => `Preset ${index}`)
    const run = await startWithAcceptedSequence(presets, {}, { segment_count: 6 })
    await run.project.processBrowserCommand({ type: 'append_prompt', prompt: 'The ending', prompt_id: 'append' })
    await finishRound(run, ['The ending'])
    const source = run.project.completedSequencePrompts
    expect(source).toHaveLength(7)
    await run.project.processBrowserCommand({
      type: 'rewrite_seed_prompts', rewrite_instruction: 'Add rain', prompt_id: 'rewrite', prompt_window_prompts: source,
    })
    const scenes = Array.from({ length: 7 }, (_value, index) => `Scene ${index + 1}`)
    await finishRound(run, scenes)
    expect(run.generation.calls).toHaveLength(14)
    expect(run.project.completedSequencePrompts).toEqual(scenes)
    expect(harness!.enhancer.rewriteRollout.mock.calls[0]![1].promptsToRewrite).toEqual(source)
    expect(rolloutText(7)).toBe(run.socket.eventsOfType('seed_prompts_updated')[0]!['raw_llm_output'])
  })

  it('stops waiting for the rollout on close, logs the cancelled rewrite, and submits nothing', async () => {
    const enhancer = new FakePromptEnhancer()
    const run = await startWithAcceptedSequence(['Accepted scene'], { enhancer })
    const entered = new Deferred()
    enhancer.rewriteRollout.mockImplementationOnce(async () => {
      entered.resolve()
      return await new Promise<never>(() => {})
    })
    await run.project.processBrowserCommand({ type: 'rewrite_seed_prompts', rewrite_instruction: 'Change scene' })
    await within(entered.promise)
    await within(run.project.closeAndWaitForGeneration())
    expect(enhancer.rewriteRollout.mock.calls[0]![1].signal.aborted).toBe(true)
    expect(await within(run.outcome)).toBeNull()
    expect(run.generation.calls).toHaveLength(1)
    expect(run.project.completedSequencePrompts).toEqual(['Accepted scene'])
    expect(harness!.logEvents('rewrite_cancelled')).toEqual([logEntry('rewrite_cancelled', {
      kind: 'seed_rewrite', rewrite_instruction: 'Change scene', rewrite_model: 'model-a',
    })])
  })

  it('rejects a rewrite during generation and finishes the admitted plan', async () => {
    harness = await openUserActions()
    const run = await harness.start(projectPayload({ curated_prompts: ['segment one prompt', 'segment two prompt'] }))
    const first = await run.generation.nextCall()
    const after = run.socket.entries.length
    await run.project.processBrowserCommand({ type: 'rewrite_seed_prompts', rewrite_instruction: 'restart from rewrite' })
    expect(run.socket.events(after)).toEqual([{
      type: 'error', prompt_id: null, message: 'Wait for this generation round to finish before changing the video.',
    }])
    first.finish.resolve()
    const second = await run.generation.nextCall()
    second.finish.resolve()
    await run.socket.waitForStatus('idle', after)
    expect(run.generation.calls.map(call => call.request.prompt)).toEqual(['segment one prompt', 'segment two prompt'])
    expect(harness.logEvents('rewrite_done')).toEqual([])
    expect(harness.enhancer.rewriteRollout).not.toHaveBeenCalled()
  })
})
