/**
 * Run the six-step test case of the video harness design through the structured tools and print the folded state
 * after each step. Shots come from the fake generation backend by default; set `VH_BACKEND_URL` to generate through a
 * running DreamVerse backend instead. Exits non-zero when a stated expectation fails.
 * Run with `pnpm exec tsx scripts/video-harness/walkthrough.ts`.
 */
import { existsSync } from 'node:fs'
import { brandString } from '@deepseek-ai/dsh-brand'
import type { AssetId, EntityId, OpId, ProjectId } from '@video-harness/oplog'
import { ffmpegAvailable, type ProjectState } from '@video-harness/runtime'
import { FFMPEG, startTools } from '../../packages/video-harness/tools/tests/support.ts'

/** The reference image used with a real backend. */
const REAL_REFERENCE = '/mnt/lustre/vlm-d1su/codes/dsh-dv-hub/elon-musk.jpg'
const BACKEND_URL = process.env['VH_BACKEND_URL']

let failures = 0

/** Record an expectation; a false one is printed and counted. */
function expect(condition: boolean, message: string): void {
  console.log(`  ${condition ? 'ok  ' : 'FAIL'} ${message}`)
  if (!condition) failures += 1
}

/** One line per fact a view would show. */
function summarize(label: string, state: ProjectState, heads: Record<string, OpId>): void {
  const slots = state.sequence?.items.map(item => `${item.slot}:${item.assetId.slice(0, 6)}${item.inSec === null ? '' : `[${item.inSec}-${item.outSec ?? ''}]`}`) ?? []
  console.log(`\n== ${label}`)
  console.log(`  ops=${state.ops.length} head=${state.head.slice(0, 8)} branches=${Object.keys(heads).join(',')}`)
  console.log(`  sequence=[${slots.join(' ')}] stale=${Object.keys(state.stale).length} takes=${Object.values(state.takes).map(list => list.length).join('/')}`)
}

/** The scripted test case; every step is one or more `invoke` calls through the runtime, with the real tool specs. */
async function main(): Promise<void> {
  if (!(await ffmpegAvailable(FFMPEG))) {
    console.error(`ffmpeg not available at ${FFMPEG}; set VH_FFMPEG to run the walkthrough.`)
    process.exit(2)
  }
  const real = BACKEND_URL !== undefined
  const fixture = await startTools({ dsh: false, perception: false, generation: real ? { baseUrl: BACKEND_URL } : 'fake' })
  const { project, log } = fixture
  const facts = real ? await fixture.context.dreamverseGeneration.model() : fixture.generation.facts
  const duration = facts.minSegmentDurationSec
  console.log(`backend: ${real ? BACKEND_URL : 'fake'} (${facts.modelId}); shots of ${duration}s`)
  const projectId: ProjectId = project.createProject({ title: 'dance' })
  const user = { actor: 'user' as const, surface: 'chat' as const }
  const agent = { actor: 'agent' as const, surface: 'chat' as const }
  const reference = real && existsSync(REAL_REFERENCE) ? REAL_REFERENCE : fixture.writeFile('person.png')
  const referenceMime = reference.endsWith('.jpg') ? 'image/jpeg' : 'image/png'

  // Step 1: upload, intent, plan, approve, three chained shots, sequence.
  const t1 = project.beginTurn(projectId, { ...user, intent: '给我一个这个人跳舞的视频' })
  const upload = await project.invoke(projectId, { tool: 'asset.upload', inputs: [], params: { path: reference, mime: referenceMime }, ...user, intent: 'upload', turn: t1.turn })
  const a1 = upload.outputs[0] as AssetId
  const t2 = project.beginTurn(projectId, { ...agent, intent: 'plan' })
  await project.invoke(projectId, { tool: 'entity.character.create', inputs: [], params: { entity: 'c1', name: '主角', refs: [a1] }, ...agent, intent: 'register character', turn: t2.turn })
  const plan = await project.invoke(projectId, {
    tool: 'plan.create', inputs: [], ...agent, intent: 'plan 3 chained shots', turn: t2.turn,
    params: { continuity: 'chained', references: ['c1@1'], shots: [1, 2, 3].map(index => ({ prompt: `Picture 1 dancing, shot ${index}`, duration_sec: duration })) },
  })
  project.acceptTurn(projectId, t2.turn)
  let state = project.fold(projectId)
  expect(state.plans.length === 1 && !state.plans[0]?.approved, 'plan recorded, awaiting approval')
  const t3 = project.beginTurn(projectId, { ...user, intent: 'approve plan' })
  const approve = await project.invoke(projectId, { tool: 'plan.approve', inputs: [], params: { plan: plan.id }, ...user, intent: 'approve plan', turn: t3.turn })
  expect(approve.kind === 'approve', 'approval is an approve record')
  await project.whenIdle(projectId)
  state = project.fold(projectId)
  const shots = state.ops.filter(op => op.tool?.name === 'generate.video').map(op => op.id)
  const clips = shots.map(id => log.get(projectId, id).outputs[0] as AssetId)
  summarize('step 1: plan + 3 chained shots', state, log.heads(projectId))
  expect(shots.length === 3 && shots.every(id => log.get(projectId, id).status === 'done'), 'three shots generated by the scheduler')
  expect(log.get(projectId, shots[1] as OpId).inputs.some(input => input.role === 'first_frame' && input.resolved === log.get(projectId, shots[0] as OpId).outputs[1]), 'shot 2 starts from the last frame of shot 1')
  expect(state.sequence?.items.length === 3, 'sequence has 3 slots')
  expect(state.plans[0]?.approved === true, 'plan approved')
  expect(Object.keys(state.stale).length === 0, 'nothing stale')
  expect(state.entities[brandString<EntityId>('c1')]?.length === 1, 'character c1 at version 1')

  // Step 1b: the same plan with independent shots, on an exploration branch so main keeps the chained result.
  project.createBranch(projectId, 'independent', 'main')
  const tb = project.beginTurn(projectId, { ...agent, intent: 'independent shots', branch: 'independent' })
  const planB = await project.invoke(projectId, {
    tool: 'plan.create', inputs: [], ...agent, intent: 'plan 2 independent shots', turn: tb.turn,
    params: { continuity: 'independent', references: ['c1@1'], shots: [1, 2].map(index => ({ prompt: `Picture 1 dancing alone, shot ${index}`, duration_sec: duration })) },
  })
  await project.invoke(projectId, { tool: 'plan.approve', inputs: [], params: { plan: planB.id }, ...user, intent: 'approve plan B', turn: tb.turn })
  await project.whenIdle(projectId)
  const branchB = project.fold(projectId, 'independent')
  const shotsB = branchB.ops.filter(op => op.tool?.name === 'generate.video' && op.params['plan'] === planB.id)
  summarize('step 1b: independent plan on branch "independent"', branchB, log.heads(projectId))
  expect(shotsB.length === 2 && shotsB.every(op => op.status === 'done' && op.inputs.every(input => input.role === 'reference')), 'independent shots carry only the reference')
  expect(branchB.sequence?.items.length === 2 && project.fold(projectId).sequence?.items.length === 3, 'each branch folds its own sequence')

  // Step 2: trim the start of shot 2 (deterministic, cheap: runs on main directly).
  const t4 = project.beginTurn(projectId, { ...user, intent: '剪掉第二段的开头' })
  const slot2 = state.sequence?.items[1]?.assetId as AssetId
  const trim = await project.invoke(projectId, { tool: 'clip.trim', inputs: [{ role: 'clip', ref: slot2 }], params: { startSec: 0.5 }, ...agent, intent: 'trim shot 2', turn: t4.turn })
  await project.invoke(projectId, { tool: 'sequence.replace', inputs: [], params: { slot: 2, asset: trim.outputs[0] }, ...agent, intent: 'replace slot 2', turn: t4.turn })
  state = project.fold(projectId)
  summarize('step 2: trim shot 2', state, log.heads(projectId))
  expect(state.sequence?.items[1]?.assetId === trim.outputs[0], 'slot 2 shows the trimmed clip')
  expect(!(shots[2] as OpId in state.stale), 'shot 3 is not stale after the trim')
  const cachedTrim = await project.invoke(projectId, { tool: 'clip.trim', inputs: [{ role: 'clip', ref: slot2 }], params: { startSec: 0.5 }, ...agent, intent: 'trim again', turn: t4.turn })
  expect(cachedTrim.cost?.cached === true && cachedTrim.outputs[0] === trim.outputs[0], 'repeating the trim hits the deterministic cache')
  const stateAfterStep2 = project.fold(projectId)

  // Step 3: regenerate shot 3 from a side angle as a draft take, then accept.
  const t5 = project.beginTurn(projectId, { ...agent, intent: '第三段换一个侧面的镜头角度' })
  const shot3 = log.get(projectId, shots[2] as OpId)
  const retake = await project.invoke(projectId, {
    tool: 'generate.video', inputs: shot3.inputs.map(input => ({ role: input.role, ref: input.ref })),
    params: { ...shot3.params, prompt: 'Picture 1 dancing, shot 3, side angle' }, ...agent, intent: 'retake shot 3', turn: t5.turn, base_op: shot3.id,
  })
  await project.invoke(projectId, { tool: 'sequence.replace', inputs: [], params: { slot: 3, asset: retake.outputs[0] }, ...agent, intent: 'use retake', turn: t5.turn })
  expect(project.fold(projectId, t5.branch).turns[t5.turn]?.accepted === false, 'draft turn is not accepted while open')
  expect(project.fold(projectId).sequence?.items[2]?.assetId === clips[2], 'main still shows the original shot 3 while the draft is open')
  project.acceptTurn(projectId, t5.turn)
  state = project.fold(projectId)
  summarize('step 3: side-angle retake accepted', state, log.heads(projectId))
  expect(state.sequence?.items[2]?.assetId === retake.outputs[0], 'slot 3 shows the retake')
  expect((state.takes[shot3.id] ?? []).length === 2, 'shot 3 has two takes')

  // Step 4: the user replaces the character reference on the canvas; dependents go stale, nothing reruns by itself.
  const t6 = project.beginTurn(projectId, { actor: 'user', surface: 'canvas', intent: '换人物参考图' })
  const upload2 = await project.invoke(projectId, { tool: 'asset.upload', inputs: [], params: { path: real ? reference : fixture.writeFile('person2.png'), mime: referenceMime, name: 'person2' }, actor: 'user', surface: 'canvas', intent: 'upload', turn: t6.turn })
  await project.invoke(projectId, { tool: 'entity.character.update', inputs: [], params: { entity: 'c1', refs: [upload2.outputs[0]] }, actor: 'user', surface: 'canvas', intent: 'replace reference', turn: t6.turn })
  state = project.fold(projectId)
  summarize('step 4: character reference replaced', state, log.heads(projectId))
  expect(state.entities[brandString<EntityId>('c1')]?.length === 2, 'c1 at version 2')
  expect(shots.every(id => id in state.stale), 'all three original shots are stale')
  expect(retake.id in state.stale, 'the retake is stale too')
  expect(trim.id in state.stale, 'the trim is stale through its stale input')
  const opsBeforeReplay = state.ops.length
  // The agent regenerates shot 2 with the new reference and declares it the replacement: the trim replays by itself.
  const t6b = project.beginTurn(projectId, { ...agent, intent: '用新参考图重做第二段' })
  const shot2 = log.get(projectId, shots[1] as OpId)
  const regenerated = await project.invoke(projectId, {
    tool: 'generate.video', inputs: shot2.inputs.map(input => ({ role: input.role, ref: input.role === 'reference' ? 'c1@2' : input.ref })),
    params: { ...shot2.params, prompt: `${String(shot2.params['prompt'])}, new reference` }, ...agent, intent: 'regenerate shot 2', turn: t6b.turn, base_op: shot2.id, supersedes: [shot2.id],
  })
  await project.whenIdle(projectId)
  project.acceptTurn(projectId, t6b.turn)
  state = project.fold(projectId)
  summarize('step 4b: shot 2 regenerated, trim replayed automatically', state, log.heads(projectId))
  const replayedTrim = state.ops.find(op => op.tool?.name === 'clip.trim' && op.base_op === trim.id && op.params['replayed_from'] === trim.id)
  expect(replayedTrim?.status === 'done' && replayedTrim.actor === 'system', 'the trim was replayed by the runtime on the regenerated shot')
  expect(replayedTrim?.inputs[0]?.resolved === regenerated.outputs[0], 'the replay reads the new shot')
  expect(state.sequence?.items[1]?.assetId === replayedTrim?.outputs[0], 'slot 2 shows the replayed trim')
  expect(!(shots[1] as OpId in state.stale) || state.superseded[shots[1] as OpId] === regenerated.id, 'the original shot 2 is superseded by the regeneration')
  expect(state.ops.length > opsBeforeReplay + 2, 'replay records were appended')

  // Step 5: reorder on the timeline; no asset changes, so nothing new becomes stale.
  const t7 = project.beginTurn(projectId, { actor: 'user', surface: 'timeline', intent: '把第 3 段移到第 2 段前' })
  const staleBefore = Object.keys(project.fold(projectId).stale).length
  await project.invoke(projectId, { tool: 'sequence.move', inputs: [], params: { from: 3, to: 2 }, actor: 'user', surface: 'timeline', intent: 'reorder', turn: t7.turn })
  state = project.fold(projectId)
  summarize('step 5: reorder', state, log.heads(projectId))
  expect(state.sequence?.items[1]?.assetId === retake.outputs[0] && state.sequence?.items[2]?.assetId === replayedTrim?.outputs[0], 'slots 2 and 3 swapped')
  expect(Object.keys(state.stale).length === staleBefore, 'reorder adds no staleness')

  // Step 6: undo the latest turn, then branch from the end of step 2 for another style.
  const undone = project.undoLatestTurn(projectId)
  state = project.fold(projectId)
  expect(undone === t7.turn && state.sequence?.items[1]?.assetId === replayedTrim?.outputs[0], 'undo of the reorder turn restores the order')
  project.createBranch(projectId, 'style-b', stateAfterStep2.head)
  const branchState = project.fold(projectId, 'style-b')
  summarize('step 6: branch style-b from after step 2', branchState, log.heads(projectId))
  expect(branchState.sequence?.items.map(item => item.assetId).join() === stateAfterStep2.sequence?.items.map(item => item.assetId).join(), 'style-b folds to the step-2 sequence')
  expect(Object.keys(branchState.stale).length === 0, 'style-b has no stale records (the reference change happened later on main)')
  expect(project.fold(projectId).entities[brandString<EntityId>('c1')]?.length === 2, 'main still has c1 at version 2')

  // Restart: a fresh harness over the same root folds the same state.
  await fixture.context.fiber.dispose()
  const again = await startTools({ root: fixture.root, dsh: false, perception: false, generation: 'none' })
  const reloaded = again.project.fold(projectId)
  expect(reloaded.ops.length === state.ops.length && reloaded.head === state.head, 'state survives a restart')
  await again.dispose()
  console.log(failures === 0 ? '\nwalkthrough passed' : `\nwalkthrough failed: ${failures} expectation(s)`)
  process.exit(failures === 0 ? 0 : 1)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
